In [1]:
print("array spliting!")

array spliting!


In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
print(np.array_split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [6]:
newarray = np.array_split(arr,3)

In [7]:
print(newarray[0])

[1 2]


In [8]:
print(newarray[1])

[3 4]


###### 2D array spliting

In [9]:
twoDarray = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [10]:
print(twoDarray)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
print(twoDarray[2][0])

5


In [12]:
print(np.array_split(twoDarray,3))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [13]:
new2Darray = np.array_split(twoDarray,3)

In [14]:
print(new2Darray)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [15]:
print(new2Darray[0])
print(new2Darray[1])
print(new2Darray[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
