In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr[0])

1


In [4]:
print(arr[1])
print(arr[2]+arr[3])

2
7


#### Access 2D array

In [5]:
twoDarray = np.array([[2,4,6],[1,3,5]])
print(twoDarray)

[[2 4 6]
 [1 3 5]]


In [6]:
print(twoDarray[0,1])

4


In [7]:
print(twoDarray[1,1])

3


##### Access 3-D array

In [8]:
threeDarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(threeDarray[0,1,2])
print(threeDarray[1,0,2])
print(threeDarray[1,1,1])

6
9
11
