In [2]:
print("array reshape!")
import numpy as np

array reshape!


In [3]:
oneDarray = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

###### convert 1D to 2D array

In [4]:
twoDarrya = oneDarray.reshape(4,3)

In [5]:
print(twoDarrya,twoDarrya.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 2
