In [1]:
print("numpy array join")

numpy array join


In [2]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
Arr = np.concatenate((arr1,arr2))
print(Arr)

[ 1  2  3  4  5  6  7  8  9 10]


##### 2d array join

In [6]:
twoDarr1 = np.array([[1,3,5],[7,9,11]])
twoDarr2 = np.array([[2,4,6],[8,10,12]])
twoDarr = np.concatenate((twoDarr1,twoDarr2),axis=1)
print(twoDarr)

[[ 1  3  5  2  4  6]
 [ 7  9 11  8 10 12]]


In [ ]:
)