In [1]:
print("Copy vs View in numpy")

Copy vs View in numpy


In [2]:
import numpy as np

##### numpy array copy

In [3]:
arr = np.array([1,3,5,7,9])
x = arr.copy()

In [4]:
print(arr)
print(x)

[1 3 5 7 9]
[1 3 5 7 9]


In [5]:
arr[0] = 50

In [6]:
print(arr)

[50  3  5  7  9]


In [7]:
print(x)

[1 3 5 7 9]


##### numpy array view

In [8]:
varr = np.array([2,4,6,8,10])

In [9]:
y = varr.view()

In [10]:
print(varr)

[ 2  4  6  8 10]


In [11]:
print(y)

[ 2  4  6  8 10]


In [12]:
y[0] = 20

In [13]:
print(varr)
print(y)

[20  4  6  8 10]
[20  4  6  8 10]


In [14]:
print(x.base)
print(y.base)

None
[20  4  6  8 10]


##### numpy array shape

In [16]:
twoDarray = np.array([[2,4,6,8],[1,3,5,7]])

In [17]:
print(twoDarray.ndim)

2


In [18]:
print(twoDarray.shape)

(2, 4)


In [19]:
threeDarray = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])

In [21]:
print(threeDarray.ndim)

3


In [22]:
print(threeDarray.shape)

(2, 2, 3)
