In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


### use tuple to create a numpy array

In [5]:
tupleArray = np.array((5,6,7,8))

In [6]:
print(tupleArray)

[5 6 7 8]


### 0D array

In [7]:
print(np.array(30))

30


### 1D array

In [8]:
print(np.array([1,3,5,7]))

[1 3 5 7]


### 2D array

In [9]:
print(np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


### 3D array

In [10]:
threeD = np.array([[[10,20],[30,40]],[[10,20],[50,60]]])
print(threeD)

[[[10 20]
  [30 40]]

 [[10 20]
  [50 60]]]


In [11]:
# check dimension
print(threeD.ndim)
# ndim attribute that returns an integer that tells us how many dimensions the array have.

3


### Higher dimensional array

In [12]:
hArray = np.array([1,2,3,45], ndmin=5)

In [13]:
print(hArray)

[[[[[ 1  2  3 45]]]]]


In [14]:
print(hArray.ndim)

5
