In [1]:
import numpy as np
k =np.array([[1,1,2,3,],[4,5,6,9],[7,8,5,41]])
print(k)

[[ 1  1  2  3]
 [ 4  5  6  9]
 [ 7  8  5 41]]


In [2]:
k[:,1:2]

array([[1],
       [5],
       [8]])

In [3]:
for i in range(4):
    for j in range(i):
        print(" ", end="")
    for k in range(4 - i):
        print("*", end="")
    print()


****
 ***
  **
   *


In [4]:
rows = 4  # Number of rows in the pattern

for i in range(rows):
    print(" " * (2 * i), "*" * (rows - i))


 ****
   ***
     **
       *


In [5]:
rows = 4

for i in range(rows):
    print(" " * i + "*" * (rows - i))


****
 ***
  **
   *
