In [62]:
import numpy as np
cpu_demands = input("Enter the reference string[separate them by commas] : ",)
print(cpu_demands)
# test case 1 : 2,3,2,1,5,2,4,5,3,2,5,2 ; frame = 3(sir)
# test case 2 : 7,0,1,2,0,3,0,4,2,3,0,3,1,2,0 ; frame = 3

7,0,1,2,0,3,0,4,2,3,0,3,1,2,0


In [63]:
cpu_demands_list = cpu_demands.split(",")
cpu_demands_list = np.array(cpu_demands_list)
reference_string = [int(i) for i in cpu_demands_list]

print(reference_string)

[7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 1, 2, 0]


In [64]:
frames = int(input("enter the total number of frames: "))

In [65]:

frames_list = np.empty((frames,len(reference_string)),dtype=object)
print(frames_list)
print(reference_string)
    

[[None None None None None None None None None None None None None None
  None]
 [None None None None None None None None None None None None None None
  None]
 [None None None None None None None None None None None None None None
  None]]
[7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 1, 2, 0]


In [66]:
f_c_value = 0
f_c_queue = []
mis_or_hi = []
# if f_c_value < len(reference_string):
#     for j in range(len)
for i in range(len(reference_string)):
    # print(frames_list)
    if np.all(frames_list == None):
        frames_list[0][i] = reference_string[i]
        f_c_queue.append(reference_string[i])
        mis_or_hi.append("M")
        # print("again \n")
    else:
        f_c_queue.append(reference_string[i])
        flag = 0
        flag1 = 0
        columns = len(frames_list)
        for a in range(len(frames_list)):
            if frames_list[a][i-1] != reference_string[i]:
                flag+=1
                # if len(f_c_queue) == i:
                #     f_c_queue.append(reference_string[i])
            if columns == flag:
                # if len(f_c_queue) == i:
                #     f_c_queue.append(reference_string[i])
                # print('hi')
                j=0
                while j < len(frames_list):
                    if frames_list[j][i-1] == None:
                        frames_list[j][i] = reference_string[i]
                        break
                    else:
                        frames_list[j][i] = frames_list[j][i-1]
                        flag1+=1
                        if columns == flag1:# updating fc value
                            j = 0
                            while j < len(frames_list):
                                if frames_list[j][i] == f_c_queue[f_c_value]:
                                    frames_list[j][i] = reference_string[i]
                                    f_c_value+=1
                                    break
                                j+=1
                    j+=1
                mis_or_hi.append('M')
            # print("j = :",a)
            if frames_list[a][i-1] == reference_string[i]:
                f_c_queue.pop()
                j = 0
                while j < len(frames_list):
                    frames_list[j][i] = frames_list[j][i-1]
                    j+=1
                mis_or_hi.append('H')
                # f_c_value+=1 # if hit
                


        
    # print(frames_list[:,i])
    # print(f_c_queue)
    # print(f_c_value)
print("--------------")

print(frames_list)
print(len(frames_list))
print("------------------")
print('reference string: ',reference_string)
for i in range(len(reference_string)):
    if np.any(frames_list[:, i] == None):
        frames_list[np.where(frames_list[:, i] == None), i] = 0
print(frames_list)
# print('queue: ',f_c_queue)
print(mis_or_hi)


--------------
[[7 7 7 2 2 2 2 4 4 4 0 0 0 0 0]
 [None 0 0 0 0 3 3 3 2 2 2 2 1 1 1]
 [None None 1 1 1 1 0 0 0 3 3 3 3 2 2]]
3
------------------
reference string:  [7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 1, 2, 0]
[[7 7 7 2 2 2 2 4 4 4 0 0 0 0 0]
 [0 0 0 0 0 3 3 3 2 2 2 2 1 1 1]
 [0 0 1 1 1 1 0 0 0 3 3 3 3 2 2]]
['M', 'M', 'M', 'M', 'H', 'M', 'M', 'M', 'M', 'M', 'M', 'H', 'M', 'M', 'H']


In [67]:
a = [1]
print(len(a))

1


In [68]:
total_hit = 0
total_miss = 0
for l in range(len(mis_or_hi)):
    if mis_or_hi[l] == 'M':
        total_miss+=1
    else:
        total_hit+=1
print(total_miss,total_hit)
ratio_of_hit = (total_hit/len(mis_or_hi))*100
ratio_of_miss = (total_miss/len(mis_or_hi)*100)
print("Ratio of miss and hit: ", ratio_of_miss,ratio_of_hit)

12 3
Ratio of miss and hit:  80.0 20.0
