In [1]:
import numpy as np
cpu_demands = input("Enter the reference string[separate them by commas] : ",)
print(cpu_demands)

# test case 1 : 2,3,2,1,5,2,4,5,3,2,5,2 ; frame = 3(sir)

2,3,2,1,5,2,4,5,3,2,5,2


In [2]:
cpu_demands_list = cpu_demands.split(",")
cpu_demands_list = np.array(cpu_demands_list)
reference_string = [int(i) for i in cpu_demands_list]

print(reference_string)

[2, 3, 2, 1, 5, 2, 4, 5, 3, 2, 5, 2]


In [3]:
frames = int(input("enter the total number of frames: "))

In [14]:
frames_list = np.empty((frames,len(reference_string)),dtype=object)
print(frames_list)
print(reference_string)


[[None None None None None None None None None None None None]
 [None None None None None None None None None None None None]
 [None None None None None None None None None None None None]]
[2, 3, 2, 1, 5, 2, 4, 5, 3, 2, 5, 2]


In [15]:
for i in range(len(reference_string)):
    if np.all(frames_list == None):
        frames_list[0][i] = reference_string[i]
    else:
        flag = 0
        flag1 = 0
        flag2 = 0
        columns = len(frames_list)
        
        for a in range(len(frames_list)):
            if frames_list[a][i-1] != reference_string[i]:
                flag+=1
            if columns == flag:
                j = 0
                while j < len(frames_list):
                    if frames_list[j][i-1] == None:
                        frames_list[j][i] = reference_string[i]
                        break
                    else:
                        frames_list[j][i] = frames_list[j][i-1]
                        flag1+=1
                        if columns == flag1:
                            part_of_ref_string = []
                            part_of_ref_string = np.array(part_of_ref_string)
                            part_of_ref_string = reference_string[i:]
                            print(part_of_ref_string)
                            page_track = []
                            k = 0
                            while k < len(frames_list):
                                for p in range(len(part_of_ref_string)):
                                    if frames_list[k][i] == part_of_ref_string[p]:
                                        page_track.append(p)
                                        flag2+=1
                                        if flag2 == columns:
                                            print(page_track)
                                            max_value = max(page_track)
                                            h = 0
                                            while h < len(frames_list):
                                                if frames_list[h][i] == page_track[max_value]:
                                                    frames_list[h][i] = reference_string[i]
                                                h+=1
                                    elif np.any(part_of_ref_string != frames_list[k][i]):
                                        frames_list[k][i] = reference_string[i]
                                        break
                                        
                                k+=1
                    j+=1
            if frames_list[a][i-1] == reference_string[i]:
                j = 0
                while j < len(frames_list):
                    frames_list[j][i] = frames_list[j][i-1]
                    j+=1
                
                            
            

print(frames_list)
print("------------")
for i in range(len(reference_string)):
    if np.any(frames_list[:, i] == None):
        frames_list[np.where(frames_list[:, i] == None), i] = 0
print(frames_list)

[5, 2, 4, 5, 3, 2, 5, 2]
[2, 4, 5, 3, 2, 5, 2]
[4, 5, 3, 2, 5, 2]
[5, 3, 2, 5, 2]
[3, 2, 5, 2]
[2, 5, 2]
[5, 2]
[2]
[[2 2 2 2 5 2 4 5 3 2 5 2]
 [None 3 3 3 5 2 4 5 3 2 5 2]
 [None None None 1 5 2 4 5 3 2 5 2]]
------------
[[2 2 2 2 5 2 4 5 3 2 5 2]
 [0 3 3 3 5 2 4 5 3 2 5 2]
 [0 0 0 1 5 2 4 5 3 2 5 2]]
