In [1]:
import numpy as np
cpu_demands = input("Enter the reference string[separate them by commas] : ",)
print(cpu_demands)

# test case 1 : 2,3,2,1,5,2,4,5,3,2,5,2 ; frame = 3(sir)

2,3,2,1,5,2,4,5,3,2,5,2


In [2]:
cpu_demands_list = cpu_demands.split(",")
cpu_demands_list = np.array(cpu_demands_list)
reference_string = [int(i) for i in cpu_demands_list]

print(reference_string)

[2, 3, 2, 1, 5, 2, 4, 5, 3, 2, 5, 2]


In [3]:
frames = int(input("enter the total number of frames: "))

In [22]:
frames_list = np.empty((frames,len(reference_string)),dtype=object)
print(frames_list)
print(reference_string)


[[None None None None None None None None None None None None]
 [None None None None None None None None None None None None]
 [None None None None None None None None None None None None]]
[2, 3, 2, 1, 5, 2, 4, 5, 3, 2, 5, 2]


In [23]:
mis_or_hit = []
for i in range(len(reference_string)):
    if np.all(frames_list == None):
        frames_list[0][i] = reference_string[i]
        mis_or_hit.append("M")
    else:
        flag,flag1,flag2 = 0, 0 , 0
        flag3 = False
        flag4 = False
        columns = len(frames_list)
        
        for a in range(len(frames_list)):
            
            if frames_list[a][i-1] != reference_string[i]:
                flag+=1
            if columns == flag:
                j=0
                while j < len(frames_list):
                    if frames_list[j][i-1] == None:
                        frames_list[j][i] = reference_string[i]
                        break
                    else:
                        frames_list[j][i] = frames_list[j][i-1]
                        flag1+=1
                        
                        if columns == flag1:
                            part_of_ref_string = []
                            part_of_ref_string = np.array(part_of_ref_string)
                            part_of_ref_string = reference_string[i:]
                            print(part_of_ref_string)
                            page_track = []
                            
                            k = 0
                            while k < len(frames_list):
                                for p in range(len(part_of_ref_string)):
                                    
                                    if frames_list[k][i] not in part_of_ref_string and flag4 == False:
                                        print("this one : ",frames_list[k][i])
                                        frames_list[k][i] = reference_string[i]
                                        l = 0
                                        while l < len(frames_list):
                                            if k != l:
                                                frames_list[l][i] = frames_list[l][i-1]
                                            l+=1
                                        page_track = []
                                        flag3 = True
                                        flag4 = True
                                        # mis_or_hit.append("M")
                                        break
                                    if frames_list[k][i] == part_of_ref_string[p] and flag3 == False:
                                        page_track.append(p)
                                        break
                                k+=1
                            print("pages: ",page_track)
                            if len(page_track) != 0:
                                max_value = max(page_track)
                                print(part_of_ref_string[max_value])
                                c = 0
                                while c < len(frames_list):
                                    if frames_list[c][i] == part_of_ref_string[max_value]:
                                        frames_list[c][i] = reference_string[i]
                                    else:
                                        frames_list[c][i] = frames_list[c][i-1]
                                    c+=1
                                
#                                 print("it has")
                            else:
#                                 print("it hasn't")
                                break
                    
                    j+=1
                mis_or_hit.append("M")    
                    
                    
            if frames_list[a][i-1] == reference_string[i]:
                j = 0
                while j < len(frames_list):
                    frames_list[j][i] = frames_list[j][i-1]
                    j+=1
                mis_or_hit.append("H")
                

print(frames_list)
print("------------final output---------")
for i in range(len(reference_string)):
    if np.any(frames_list[:, i] == None):
        frames_list[np.where(frames_list[:, i] == None), i] = 0
print(frames_list)
print(mis_or_hit)

[5, 2, 4, 5, 3, 2, 5, 2]
this one :  1
pages:  []
[4, 5, 3, 2, 5, 2]
pages:  [3, 2, 1]
2
[2, 5, 2]
this one :  4
pages:  []
[[2 2 2 2 2 2 4 4 4 2 2 2]
 [None 3 3 3 3 3 3 3 3 3 3 3]
 [None None None 1 5 5 5 5 5 5 5 5]]
------------final output---------
[[2 2 2 2 2 2 4 4 4 2 2 2]
 [0 3 3 3 3 3 3 3 3 3 3 3]
 [0 0 0 1 5 5 5 5 5 5 5 5]]
['M', 'M', 'H', 'M', 'M', 'H', 'M', 'H', 'H', 'M', 'H', 'H']


In [21]:
total_hit = 0
total_miss = 0
for l in range(len(mis_or_hit)):
    if mis_or_hit[l] == 'M':
        total_miss+=1
    else:
        total_hit+=1
print(total_miss,total_hit)
ratio_of_hit = (total_hit/len(mis_or_hit))*100
ratio_of_miss = (total_miss/len(mis_or_hit)*100)
print("Ratio of miss and hit: ", ratio_of_miss,ratio_of_hit)

6 6
Ratio of miss and hit:  50.0 50.0
